### ISSUE TITLE
Attempting to watch missing directory: node_modules/ember-cli-foundation-6-sass/node_modules/foundation-sites/scss

### ISSUE THREAD

**Issue by devinrhode2** [acoustep/ember-cli-foundation-6-sass#5]
```
Error: Attempting to watch missing directory: node_modules/ember-cli-foundation-6-sass/node_modules/foundation-sites/scss
     at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/my-project/node_modules/broccoli-sane-watcher/index.js:90:11)
     at /my-project/node_modules/broccoli/lib/builder.js:94:35
     at lib$rsvp$$internal$$tryCatch (/my-project/node_modules/rsvp/dist/rsvp.js:493:16)
     at lib$rsvp$$internal$$invokeCallback (/my-project/node_modules/rsvp/dist/rsvp.js:505:17)
     at /my-project/node_modules/rsvp/dist/rsvp.js:1001:13
     at lib$rsvp$asap$$flush (/my-project/ember-frontend/node_modules/rsvp/dist/rsvp.js:1198:9)
     at doNTCallback0 (node.js:419:9)
     at process._tickCallback (node.js:348:13)
```

**Comment by devinrhode2** [comment]
Sorry for the lack of info, I really don't know why this is happening. I've cleared and re-installed node modules 2 times, and also did the more official `ember install ember-cli-foundation-6-sass` and got nothing.

**Comment by acoustep** [comment]
Hi @devinrhode2, I just noticed that I had not published the latest version (0.0.4) to NPM.

Can you try doing another reinstall please?

**Comment by acoustep** [comment]
Are you still having this issue?

**Comment by devinrhode2** [comment]
I uh ended up clearing all modules and fiddling around with it and eventually figured out that I probably just needed to do the ember generate command along with the other 2 install command:
```
npm install --save-dev ember-cli-sass
ember install ember-cli-foundation-6-sass
ember g ember-cli-foundation-6-sass
```
I have 0.0.4 installed right now.

**Comment by acoustep** [comment]
Great!
