### ISSUE TITLE
Addon doesn't work with Fastboot 1.0.0rc6

### ISSUE THREAD

**Issue by gandalfar** [acoustep/ember-cli-foundation-6-sass#74]
```
App is being served by FastBoot
ReferenceError: jQuery is not defined
    at /Users/gandalf/hacking/radio/frontend/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-32mVAfM5.tmp/assets/vendor.js:74650:3
    at ContextifyScript.Script.runInContext (vm.js:32:29)
    at VMSandbox.eval (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/vm-sandbox.js:14:14)
    at /Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/ember-app.js:142:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/ember-app.js:139:21)
    at EmberApp.retrieveSandboxedApp (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/ember-app.js:187:10)
    at new EmberApp (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/ember-app.js:50:21)
    at FastBoot._buildEmberApp (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/gandalf/hacking/radio/frontend/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/gandalf/hacking/radio/frontend/node_modules/ember-cli-fastboot/index.js:239:29)
    at Layer.handle [as handle_request] (/Users/gandalf/hacking/radio/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/gandalf/hacking/radio/frontend/node_modules/express/lib/router/index.js:317:13)
    at /Users/gandalf/hacking/radio/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/gandalf/hacking/radio/frontend/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/gandalf/hacking/radio/frontend/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/gandalf/hacking/radio/frontend/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then.errorHandler.buildError (/Users/gandalf/hacking/radio/frontend/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatch (/Users/gandalf/hacking/radio/frontend/node_modules/rsvp/dist/lib/rsvp/-internal.js:216:12)
    at invokeCallback (/Users/gandalf/hacking/radio/frontend/node_modules/rsvp/dist/lib/rsvp/-internal.js:231:13)
    at /Users/gandalf/hacking/radio/frontend/node_modules/rsvp/dist/lib/rsvp/then.js:29:16
    at flush (/Users/gandalf/hacking/radio/frontend/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I'm trying to follow https://gist.github.com/kratiahuja/d22de0fb1660cf0ef58f07a6bcbf1a1c to prepare a patch

**Comment by Zorig** [comment]
@gandalfar did you make the patch for that? Is project going to upgrade according to fastboot 1.0.0rc6?

**Comment by webhive** [comment]
Got the same issue :(

**Comment by Zorig** [comment]
@webhive i used this one, it's pretty cool thou https://github.com/dulmandakh/ember-cli-foundation-6

**Comment by webhive** [comment]
@Zorig Tested it but looks pretty young package and very raw implementation not so far from manual integration. This project has nice component what utilized fuondation js code.

**Comment by gandalfar** [comment]
I've made a PR that fixes this a while ago. Still waiting for any feedback on it.

**Comment by webhive** [comment]
Yes - saw it - just added my notice with hope it wil be accepted faster :)

**Comment by GCheung55** [comment]
@gandalfar thanks for the PR! Sorry for the delay. I'll review this week.
